# Generated by Django 4.0.5 on 2022-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0019_auto_20220524_1007"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(unique=True)),
                ("matricule", models.CharField(blank=True, max_length=10)),
                ("subscription", models.JSONField()),
                ("pending", models.BooleanField(default=False)),
                ("is_validated", models.BooleanField()),
                (
                    "scholar_year",
                    models.CharField(blank=True, max_length=9, verbose_name="Année scolaire"),
                ),
                ("datetime_validation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InscriptionSettingsModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("teachings", models.ManyToManyField(default=None, to="core.teachingmodel")),
            ],
        ),
    ]
